# These are supported funding model platforms

github: # https://github.com/LNshuti 
patreon: # Replace with a single Patreon username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_dev: # Replace with a single thanks.dev username
